### ISSUE TITLE
open container and press F5 error in win10

### ISSUE THREAD

**Issue by eadren** [microsoft/vscode-remote-try-rust#2]
Cargo invocation has failed: Error: could not launch cargo: Error: spawn cargo ENOENT

**Comment by Chuxel** [comment]
@eadren As you correctly identified, this is a caused by https://github.com/microsoft/vscode-remote-release/issues/544#issuecomment-498235670

**Comment by Chuxel** [comment]
#544 was fixed a while ago, let us know if you still see issues.

**Comment by Am3ra** [comment]
@Chuxel I'm getting that problem now, with  Version: 1.40.2, when trying to run Rust Unit tests. 
Checked #544 that you linked, and didn't see any obvious fixes on the client side. Any tips?
