### ISSUE TITLE
Debug Value Formatting

### ISSUE THREAD

**Issue by BDawgonnit** [microsoft/vscode-remote-try-rust#6]
I'm unsure if others have had this problem, but my debugger was not showing values in a very human-readable format after starting this up. Please see the provided screenshots of what I was seeing both before and after my fix.

![image](https://user-images.githubusercontent.com/9423873/69506712-cc943080-0efd-11ea-92a1-a91175b3298e.png)

Assuming I didn't just configure something incorrectly on my part before this step, I'd suggest the following be added to the `RUN` command of the Dockerfile in this repo to fix it:

```
    # Install Python 3 for vadimcn.vscode-lldb VSCode extension to format debugging info
    && apt-get install -y python3.6 \
```

**Comment by Chuxel** [comment]
Apologies for the delayed response - this is a good catch. 1.41 will release here soon and I'll merge the clantz/1.41 branch which includes this fix.
